matrix:
  include:
    language: python
    python:
      - "3.7"
    cache: pip
    install:
      - pip install -r requirements.txt
    script:
      - python Origamia/manage.py test Origamia
    
    language: node_js
    node_js:
      -7
    cache: 
      directories: 
        -node_modules
    install:
      - nvm install 
      - npm install -g create-react-app
    script: 
      - npm run test --prefix game
