matrix:
  include:
    language: python
    python:
      - "3.7"
    language: node_js
    node_js:
      -"stable"
cache: pip
  directories: 
    -node_modules
install:
  - pip install -r requirements.txt
  - npm install -g create-react-app
script:
  - python Origamia/manage.py test Origamia
  - npm run test --prefix game
