language: python
python:
  - "3.7"
cache: pip
cache: 
directories: 
 - "node_modules"
install:
  - pip install -r requirements.txt
 - nvm install v13.0.1
 - npm install --prefix game
script:
 - python Origamia/manage.py test Origamia
 - npm run test --prefix game
