matrix:
  include:
    language: python
    python:
      - "3.7"
    cache: pip
    install:
      - pip install -r requirements.txt
    script:
      - python Origamia/manage.py test Origamia
    
    language: node_js
    node_js:
      - "stable"
    cache: 
      directories: 
        - "node_modules"
    install:
      - nvm install v13.0.1
      - npm install --prefix game
    script: 
      - npm run test --prefix game
