# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmodel',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
